// Playwright's planner / generator / healer agents for Claude Code (#207), at
// the repo root so a session opened there — where the test guardrail hooks are
// registered — has them. See docs/md/e2e-journeys.md.
//
//   npm --prefix e2e run agents
//
// Re-run after every @playwright/test upgrade and commit the result: the agent
// definitions name the MCP tools of the Playwright they were generated by.
//
// `init-agents` writes a `.mcp.json` that only works on the OS it ran on
// (`cmd /c npx` on Windows) and that knows nothing of this repo's layout, so its
// server entry is replaced with one that runs e2e's own Playwright against
// e2e's config, on the local stack, anywhere. Other servers in the file are kept.
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const repo = path.resolve(import.meta.dirname, '../..')
const cli = 'e2e/node_modules/@playwright/test/cli.js'
const mcpPath = path.join(repo, '.mcp.json')
const specsPath = path.join(repo, 'specs')

const mcp = existsSync(mcpPath) ? JSON.parse(readFileSync(mcpPath, 'utf8')) : {}
const hadSpecs = existsSync(specsPath)

execFileSync(process.execPath, [cli, 'init-agents', '--loop=claude', '-c', 'e2e/playwright.config.ts'], {
  cwd: repo,
  stdio: 'inherit',
  // The seed is only a journey on the local stack; elsewhere init-agents would
  // not find it, and would write a blank one over it.
  env: { ...process.env, E2E_STACK: 'local' },
})

// Plans live beside the journeys, in e2e/specs/, not in a root folder of their own.
if (!hadSpecs) rmSync(specsPath, { recursive: true, force: true })

mcp.mcpServers = {
  ...mcp.mcpServers,
  'playwright-test': {
    command: 'node',
    args: [cli, 'run-test-mcp-server', '-c', 'e2e/playwright.config.ts'],
    env: { E2E_STACK: 'local' },
  },
}
writeFileSync(mcpPath, `${JSON.stringify(mcp, null, 2)}\n`)
console.log(' 🔧 .mcp.json - playwright-test runs e2e/playwright.config.ts on the local stack')
