#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: issue #74 — move both production Clerk instances onto
# reservetoday.app. This is a LIVE migration: it invalidates every existing
# production session and changes both publishable keys.
#
# Record file (gitignored) lives in .scratch/ so a Ctrl-C mid-run is resumable.
# Only publishable keys and hostnames are captured — never a secret key.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=16

mkdir -p .scratch
ENV_FILE=".scratch/clerk-prod-domain-migration.env"

CLERK_DASH="https://dashboard.clerk.com"
VERCEL_DNS="https://vercel.com/dashboard/domains"

banner "Clerk production domains → reservetoday.app (issue #74)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Read this first — what this migration breaks"
say "Two production Clerk instances move off their Vercel-generated hosts:"
note "  fe-client  clerk.booking-system-eight-fawn.vercel.app → reservetoday.app"
note "  fe-portal  clerk.project-3p3dw.vercel.app             → portal.reservetoday.app"
printf '\n'
warn "Every signed-in Yoga Sadhana member and staff member is logged out."
warn "Both publishable keys change. Until Vercel + CI are updated and redeployed,"
warn "Clerk fails to load and both apps are down. Do this in a maintenance window."
printf '\n'
say "Rollback: change the domain back in the Clerk dashboard and restore the old"
say "publishable keys (stage 2 records them). DNS records can be left in place."
printf '\n'
warn "Known contradiction in the issue's acceptance criteria — read before starting:"
note "  AC 2/3 root the instances at the shared parent domain so that ALL tenant"
note "  subdomains authenticate. Clerk does that by scoping the session cookie to"
note "  the parent domain, which means the session IS shared across subdomains."
note "  AC 7 ('a second Tenant's subdomain shows signed out') therefore cannot be"
note "  delivered by cookie scoping. Isolation comes from the app instead:"
note "  the portal via the Clerk Organization claim (spec-tenant-resolution.md §3),"
note "  the client via Origin + Row-Level Security — the client app has no orgs"
note "  at all (docs/adr/0003-no-client-side-clerk-organizations.md)."
note "  Stage 15 tests what is actually true. Expect a shared session on fe-client"
note "  with no cross-tenant data, and file that as a follow-up rather than a pass."
printf '\n'
confirm "Understood, and you are in a maintenance window?" || { say "Stopping. Nothing changed."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Rollback snapshot — record the CURRENT publishable keys"
say "Before anything changes, capture what production runs on today."
open_url "https://vercel.com/dashboard"
step "Open project 'booking-system' → Settings → Environment Variables."
step "Reveal NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY, scope Production. Copy it."
ask ROLLBACK_CLIENT_PK "Paste the CURRENT fe-client pk_live_...:"
step "Now project 'booking-system-admin' → same variable, scope Production."
ask ROLLBACK_PORTAL_PK "Paste the CURRENT fe-portal pk_live_...:"
write_env ROLLBACK_CLIENT_PK "$ROLLBACK_CLIENT_PK"
write_env ROLLBACK_PORTAL_PK "$ROLLBACK_PORTAL_PK"
note "Saved to $ENV_FILE. If you have to roll back, these are the values to restore."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Audit — Clerk dashboard state vs ADR 0001 (AC 1)"
say "ADR 0001 says ten Clerk custom-domain CNAMEs were lost in the nameserver"
say "move and nobody has checked whether Clerk still expects them. Check now."
open_url "$CLERK_DASH"
step "Pick the CLIENT application → switch the environment selector to Production."
step "Go to Configure → Domains. Note the domain shown and any 'unverified' banner."
step "Repeat for the PORTAL application's Production instance."
note "ADR 0001 names the two instances as yzxn3e3xr293 and peu4tr0s6xj5."
printf '\n'
ask AUDIT_CLIENT_DOMAIN "CLIENT production instance's current domain:"
ask AUDIT_PORTAL_DOMAIN "PORTAL production instance's current domain:"
ask AUDIT_PENDING "Any DNS records Clerk lists as unverified/pending? (short note):"
write_env AUDIT_CLIENT_DOMAIN "$AUDIT_CLIENT_DOMAIN"
write_env AUDIT_PORTAL_DOMAIN "$AUDIT_PORTAL_DOMAIN"
write_env AUDIT_PENDING "$AUDIT_PENDING"
note "This is the answer AC 1 asks for. It goes into ADR 0001 at stage 16."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "CLIENT — change the domain to reservetoday.app"
open_url "$CLERK_DASH"
step "CLIENT application → Production instance → Configure → Domains."
step "Edit the primary domain. Set it to exactly:  reservetoday.app"
step "Save. Clerk regenerates the publishable key and shows new DNS records."
warn "From this moment fe-client production is down until stage 7 redeploys it."
printf '\n'
say "Clerk also exposes this as an API call, if the dashboard fights you:"
note "  curl -XPOST -H 'Authorization: Bearer <CLIENT sk_live>' \\"
note "    -H 'Content-type: application/json' \\"
note "    -d '{\"home_url\":\"https://reservetoday.app\"}' \\"
note "    https://api.clerk.com/v1/instance/change_domain"
printf '\n'
pause "Domain changed. Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "CLIENT — create the DNS records in Vercel DNS"
say "Clerk's Domains page now lists the records it needs. Add each one in the"
say "Vercel-hosted zone. The zone is reservetoday.app on ns1/ns2.vercel-dns.com."
open_url "$VERCEL_DNS"
step "Open reservetoday.app → add a record per row Clerk shows. Expect five:"
note "  CNAME  clerk            → frontend API host"
note "  CNAME  accounts         → account portal host"
note "  CNAME  clkmail          → mail host"
note "  CNAME  clk._domainkey   → DKIM"
note "  CNAME  clk2._domainkey  → DKIM"
step "Copy each target from Clerk verbatim. Do not add a trailing dot."
warn "The zone has a '*' ALIAS, so a missing record still returns a Vercel 404"
warn "instead of NXDOMAIN (ADR 0001). You cannot detect a typo by curling it."
printf '\n'
pause "All CLIENT records added. Press Enter to verify."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "CLIENT — verify DNS + certificate"
say "Checking that the records resolve to Clerk, not to Vercel's wildcard."
printf '\n'
for host in clerk.reservetoday.app accounts.reservetoday.app clkmail.reservetoday.app; do
  printf '  %-34s ' "$host"
  target=$( { nslookup -type=CNAME "$host" 2>/dev/null || true; } | grep -iEo '[a-z0-9.-]*clerk[a-z0-9.-]*' | head -n1 )
  if [[ -n "$target" ]]; then
    printf '%s✓ CNAME → %s%s\n' "$GREEN" "$target" "$RESET"
  else
    printf '%s✗ no Clerk CNAME seen (may still be propagating)%s\n' "$YELLOW" "$RESET"
  fi
done
printf '\n'
step "Back in Clerk → Configure → Domains, every record should read 'Verified'."
note "Propagation can take minutes; Clerk allows up to 48h. Re-run this stage later."
pause "Records verified in the Clerk dashboard. Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "CLIENT — un-hardcode Home URL and Paths (AC 5)"
warn "This is the cross-tenant leak. Home URL is currently yogasadhana.reservetoday.app"
warn "and every Component path is blank, so blank paths fall back to it — a member of"
warn "any other Tenant is redirected into Yoga Sadhana's app."
printf '\n'
open_url "$CLERK_DASH"
step "CLIENT Production → Configure → Paths."
step "Set Home URL to the bare root:  https://reservetoday.app"
step "Fill every Component path with a RELATIVE path so Clerk stays on the"
step "  subdomain the user arrived at, instead of falling back to Home URL:"
note "    Sign-in           /login"
note "    Sign-up           /register"
note "    After sign-in     /"
note "    After sign-up     /"
note "    After sign-out    /"
note "  These mirror fe-client/src/app/layout.tsx, which already passes"
note "  signInUrl=\"/login\", signUpUrl=\"/register\" and relative fallbacks."
step "Save."
printf '\n'
pause "Paths saved. Press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "CLIENT — publish the new publishable key"
open_url "$CLERK_DASH"
step "CLIENT Production → API keys. Copy the NEW Publishable key (pk_live_...)."
ask NEW_CLIENT_PK "Paste the new CLIENT pk_live_...:"
write_env NEW_CLIENT_PK "$NEW_CLIENT_PK"
printf '\n'
open_url "https://vercel.com/dashboard"
step "Project 'booking-system' → Settings → Environment Variables."
step "Update NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY for the **Production** scope only."
note "Leave the Preview scope alone — staging still runs the dev instance."
pause "Vercel updated. Press Enter."
printf '\n'
say "The backend verifies member tokens with the same key, from CI:"
set_secret CLERK_CLIENT_PUBLISHABLE_KEY "$NEW_CLIENT_PK"
warn "That is a REPO secret. If the Production environment overrides it, also set it"
warn "there: gh secret set CLERK_CLIENT_PUBLISHABLE_KEY --env Production"
note "The secret key does NOT change on a domain move — leave CLERK_CLIENT_SECRET_KEY"
note "and CLERK_CLIENT_WEBHOOK_SECRET exactly as they are."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "PORTAL — change the domain to portal.reservetoday.app"
open_url "$CLERK_DASH"
step "PORTAL application → Production instance → Configure → Domains."
step "Edit the primary domain. Set it to exactly:  portal.reservetoday.app"
step "Save. A new publishable key is generated and new DNS records appear."
warn "fe-portal production is now down until stage 12 redeploys it."
printf '\n'
pause "Domain changed. Press Enter."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "PORTAL — create the DNS records in Vercel DNS"
say "Same five record types, but one label deeper."
open_url "$VERCEL_DNS"
step "reservetoday.app → add each row Clerk shows. Expect:"
note "  CNAME  clerk.portal            → frontend API host"
note "  CNAME  accounts.portal         → account portal host"
note "  CNAME  clkmail.portal          → mail host"
note "  CNAME  clk._domainkey.portal   → DKIM"
note "  CNAME  clk2._domainkey.portal  → DKIM"
warn "In Vercel DNS the 'name' field is the label relative to the zone, so type"
warn "'clerk.portal', not 'clerk.portal.reservetoday.app'."
printf '\n'
pause "All PORTAL records added. Press Enter to verify."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "PORTAL — verify DNS + certificate"
printf '\n'
for host in clerk.portal.reservetoday.app accounts.portal.reservetoday.app clkmail.portal.reservetoday.app; do
  printf '  %-40s ' "$host"
  target=$( { nslookup -type=CNAME "$host" 2>/dev/null || true; } | grep -iEo '[a-z0-9.-]*clerk[a-z0-9.-]*' | head -n1 )
  if [[ -n "$target" ]]; then
    printf '%s✓ CNAME → %s%s\n' "$GREEN" "$target" "$RESET"
  else
    printf '%s✗ no Clerk CNAME seen (may still be propagating)%s\n' "$YELLOW" "$RESET"
  fi
done
printf '\n'
step "Clerk → Configure → Domains should read 'Verified' on every row."
pause "Verified. Press Enter."

# ── 12 ────────────────────────────────────────────────────────────────────
stage "PORTAL — Paths, then publish the new publishable key"
open_url "$CLERK_DASH"
step "PORTAL Production → Configure → Paths."
step "Home URL:  https://portal.reservetoday.app   (no tenant slug in it)"
step "Component paths, relative, mirroring fe-portal/src/app/layout.tsx:"
note "    Sign-in           /login"
note "    Sign-up           /signup"
note "    After sign-in     /admin"
note "    After sign-up     /admin"
note "    After sign-out    /login"
step "Save, then open API keys and copy the NEW Publishable key."
ask NEW_PORTAL_PK "Paste the new PORTAL pk_live_...:"
write_env NEW_PORTAL_PK "$NEW_PORTAL_PK"
printf '\n'
open_url "https://vercel.com/dashboard"
step "Project 'booking-system-admin' → Settings → Environment Variables →"
step "  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY, **Production** scope only."
pause "Vercel updated. Press Enter."
set_secret CLERK_STAFF_PUBLISHABLE_KEY "$NEW_PORTAL_PK"
warn "If the Production environment overrides it, also:"
warn "  gh secret set CLERK_STAFF_PUBLISHABLE_KEY --env Production"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Both instances — leave Allowed Subdomains DISABLED (AC 6)"
say "A Tenant is created by inserting a database row, with no DNS call and no"
say "dashboard step. It therefore cannot be added to an allowlist in advance, so"
say "wildcard subdomain access has to stay on."
printf '\n'
open_url "https://dashboard.clerk.com/~/domains/allowed-subdomains"
step "CLIENT Production → 'Enable allowed subdomains' must be OFF."
step "PORTAL Production → same, OFF."
warn "Clerk's own docs recommend enabling this. We are deliberately not, and the"
warn "reason belongs in the ADR at stage 16 so nobody 'fixes' it later."
printf '\n'
pause "Both confirmed OFF. Press Enter."

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Redeploy everything that holds a publishable key"
say "New keys are only live once each app is rebuilt — NEXT_PUBLIC_* is baked in"
say "at build time, so an env change alone changes nothing."
printf '\n'
open_url "https://vercel.com/dashboard"
step "booking-system → Deployments → redeploy latest Production (uncheck cache)."
step "booking-system-admin → same."
printf '\n'
if confirm "Trigger the backend production deploy now (empty commit on main)?"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh workflow run deploy-be.yml --ref main >/dev/null 2>&1 \
      && say "Dispatched deploy-be.yml on main." \
      || { warn "Could not dispatch; run it from the Actions tab."; SKIPPED+=("backend deploy on main"); }
  else
    warn "gh not ready."
    SKIPPED+=("backend deploy on main")
  fi
else
  SKIPPED+=("backend deploy on main")
fi
printf '\n'
pause "All three deploys finished. Press Enter."

# ── 15 ────────────────────────────────────────────────────────────────────
stage "Verify — sign in, then test the cross-tenant claim (AC 7)"
printf '\n'
printf '  %-40s ' "clerk.reservetoday.app reachable?"
code=$(curl -s -m 10 -o /dev/null -w '%{http_code}' "https://clerk.reservetoday.app/v1/environment?__clerk_api_version=2021-02-05" || echo 000)
[[ "$code" == "200" ]] && printf '%s✓ 200%s\n' "$GREEN" "$RESET" || printf '%s✗ %s (404 = Vercel wildcard, i.e. record missing)%s\n' "$RED" "$code" "$RESET"
printf '  %-40s ' "clerk.portal.reservetoday.app reachable?"
code=$(curl -s -m 10 -o /dev/null -w '%{http_code}' "https://clerk.portal.reservetoday.app/v1/environment?__clerk_api_version=2021-02-05" || echo 000)
[[ "$code" == "200" ]] && printf '%s✓ 200%s\n' "$GREEN" "$RESET" || printf '%s✗ %s%s\n' "$RED" "$code" "$RESET"
printf '\n'
step "Sign in as a member at https://yogasadhana.reservetoday.app — should work."
step "Sign in as staff at https://yogasadhana.portal.reservetoday.app — should work."
step "Now open a SECOND tenant's subdomain in the same browser."
printf '\n'
warn "What to expect, per the contradiction flagged at stage 1:"
note "  PORTAL: refused. The token carries another tenant's Organization, so the"
note "  backend returns 403 tenant_mismatch (spec-tenant-resolution.md §3)."
note "  CLIENT: the session is shared — the header will very likely say signed in,"
note "  because the cookie is scoped to reservetoday.app and the client app has no"
note "  Organizations. No other tenant's DATA is reachable (Origin + RLS)."
printf '\n'
ask VERIFY_PORTAL "PORTAL second-tenant result (refused / signed in / other):"
ask VERIFY_CLIENT "CLIENT second-tenant result (signed out / signed in / other):"
write_env VERIFY_PORTAL "$VERIFY_PORTAL"
write_env VERIFY_CLIENT "$VERIFY_CLIENT"
if [[ "$VERIFY_CLIENT" == *"signed in"* ]]; then
  warn "AC 7 is NOT met on fe-client, and cannot be met by cookie scoping."
  warn "Raise a follow-up issue: fe-client must render signed-out when the signed-in"
  warn "user has no member record for the Tenant the hostname names."
  SKIPPED+=("follow-up issue: fe-client cross-tenant signed-out state (AC 7)")
fi

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Write down what actually happened (AC 8)"
say "Every value this run captured is in $ENV_FILE."
printf '\n'
step "docs/md/deployment.md — the 'Clerk instance' row of the environments table"
step "  still names the two clerk.*.vercel.app hosts. Replace with:"
note "    production — fe-client on clerk.reservetoday.app,"
note "                 fe-portal on clerk.portal.reservetoday.app"
printf '\n'
step "docs/adr/0001-… — two open questions become answered:"
note "  · 'Whether Clerk's two production instances still expect their custom"
note "     domains is unresolved' → resolved; record the stage 3 audit."
note "  · The lost-CNAME table row → the ten records are recreated, not retired."
note "  Add the Allowed Subdomains decision from stage 13 and its reason."
printf '\n'
step "Close #74 and unblock #58 (this closes its AC 3 and AC 6);"
step "  #58 AC 6's premise — 'cookie scoping is per-subdomain' — was wrong."
printf '\n'
if confirm "Open issue #74 to tick the boxes now?"; then
  open_url "https://github.com/Blueprint-Agency/booking-system/issues/74"
fi

finish
