-- Client-side Clerk Organizations are gone. See
-- docs/adr/0003-no-client-side-clerk-organizations.md.
--
-- The column stays (nullable, unique, unused) so the decision is reversible
-- without a schema change, but every value in it must go: a non-null
-- `clerk_client_org_id` is what `orgClaimVerdict` reads as "enforcement is on
-- for this studio", and member tokens carry no organization claim. Left in
-- place it would refuse every member of that studio with
-- `organization_required` — the studio's whole membership, locked out.
--
-- The Clerk organizations themselves are not deleted here, and nulling the
-- mapping without deleting them would otherwise be the *worse* of the two
-- states: an organization that still exists still puts `o.id` on the session
-- token of anyone left in it, and once it maps to no tenant that claim reads as
-- another studio's. What stops that becoming a permanent 403 is that member
-- requests no longer consult the claim at all — `middleware/clerk-client.ts`
-- does not call `assertTenantOrgClaim`, precisely so a stale organization can
-- lock nobody out. Deleting them in the client Clerk dashboard is still worth
-- doing; it is tidy-up, not a prerequisite.
update "tenants" set "clerk_client_org_id" = null where "clerk_client_org_id" is not null;
