-- Give Tenant #1 back the WhatsApp number that used to be a constant.
--
-- `fe-client/src/lib/corporate.ts` held one studio's real number, compiled into
-- the bundle every studio serves, so a member of any other studio who tapped
-- "arrange over WhatsApp" messaged Tenant #1. It now reads
-- `tenant_settings.copy->>'contact.whatsapp'`, and a studio that has published
-- no number simply does not offer the link.
--
-- Without this the rename is a silent regression for the one studio that had a
-- working link: the seed writes `tenant_settings` with ON CONFLICT DO NOTHING,
-- so it never touches a row that already exists, and there is no admin surface
-- for editing copy keys yet. The CTA on /packages and the "arrange over
-- WhatsApp" button on /account/corporate would just stop appearing.
--
-- Merged into `copy` rather than assigned over it, and skipped where the key is
-- already present, so this is a one-way backfill that cannot overwrite anything
-- a studio has since set. `jsonb_exists` rather than the `?` operator, which a
-- driver is entitled to read as a parameter placeholder.
--
-- Scoped by slug, and a no-op on any database where that studio is absent — a
-- fresh install seeds no studio at all.
-- **Edited after it was applied, and now a no-op.** The UPDATE that stood here
-- carried a real studio's telephone number and matched it by slug. It has done
-- its work everywhere it was ever going to: the one database holding that studio
-- ran it, and on any other database it matched no row at all.
--
-- What it left behind was a customer's phone number sitting in the repository,
-- which is the same class of problem the migration existed to fix — the number
-- used to be a constant in `fe-client`, compiled into every studio's bundle.
--
-- Safe to edit for the reason set out at length in 0027: the migrator skips a
-- migration by comparing the journal's `when` against the newest applied
-- `created_at`, and never re-reads the file once that timestamp is passed. The
-- journal entry is unchanged, so no database re-runs this. A studio that wants a
-- WhatsApp link publishes one in `tenant_settings.copy->>'contact.whatsapp'`.
SELECT 1;
