CREATE INDEX "clients_referred_by_client_id_fk_idx" ON "clients" USING btree ("referred_by_client_id");--> statement-breakpoint
CREATE INDEX "clients_auth_user_id_idx" ON "clients" USING btree ("auth_user_id");--> statement-breakpoint
CREATE INDEX "staff_invitations_invited_by_staff_id_fk_idx" ON "staff_invitations" USING btree ("invited_by_staff_id");--> statement-breakpoint
CREATE INDEX "staff_invitations_staff_user_id_fk_idx" ON "staff_invitations" USING btree ("staff_user_id");--> statement-breakpoint
CREATE INDEX "staff_users_archived_by_staff_id_fk_idx" ON "staff_users" USING btree ("archived_by_staff_id");--> statement-breakpoint
CREATE INDEX "staff_users_auth_user_id_idx" ON "staff_users" USING btree ("auth_user_id");--> statement-breakpoint
CREATE INDEX "class_types_parent_id_fk_idx" ON "class_types" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "instructor_class_types_class_type_id_fk_idx" ON "instructor_class_types" USING btree ("class_type_id");--> statement-breakpoint
CREATE INDEX "instructor_class_types_tenant_id_fk_idx" ON "instructor_class_types" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "instructors_tenant_id_fk_idx" ON "instructors" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "leave_conflicts_instructor_b_id_fk_idx" ON "leave_conflicts" USING btree ("instructor_b_id");--> statement-breakpoint
CREATE INDEX "leave_conflicts_tenant_id_fk_idx" ON "leave_conflicts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "merch_orders_client_id_fk_idx" ON "merch_orders" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "merch_orders_merch_id_fk_idx" ON "merch_orders" USING btree ("merch_id");--> statement-breakpoint
CREATE INDEX "global_policy_updated_by_staff_id_fk_idx" ON "global_policy" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "pt_booking_config_updated_by_staff_id_fk_idx" ON "pt_booking_config" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "client_packages_applied_promo_code_id_fk_idx" ON "client_packages" USING btree ("applied_promo_code_id");--> statement-breakpoint
CREATE INDEX "client_packages_applied_promotion_id_fk_idx" ON "client_packages" USING btree ("applied_promotion_id");--> statement-breakpoint
CREATE INDEX "client_packages_bound_instructor_id_fk_idx" ON "client_packages" USING btree ("bound_instructor_id");--> statement-breakpoint
CREATE INDEX "client_packages_location_id_fk_idx" ON "client_packages" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "client_packages_purchase_id_fk_idx" ON "client_packages" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "client_packages_source_class_package_id_fk_idx" ON "client_packages" USING btree ("source_class_package_id");--> statement-breakpoint
CREATE INDEX "client_packages_source_pt_package_id_fk_idx" ON "client_packages" USING btree ("source_pt_package_id");--> statement-breakpoint
CREATE INDEX "corporate_packages_created_by_staff_id_fk_idx" ON "corporate_packages" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "promo_code_products_tenant_id_fk_idx" ON "promo_code_products" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "promo_code_redemptions_client_id_fk_idx" ON "promo_code_redemptions" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "promo_code_redemptions_tenant_id_fk_idx" ON "promo_code_redemptions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "promo_codes_created_by_staff_id_fk_idx" ON "promo_codes" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "promotions_created_by_staff_id_fk_idx" ON "promotions" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "pt_packages_tenant_id_fk_idx" ON "pt_packages" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "class_series_class_type_id_fk_idx" ON "class_series" USING btree ("class_type_id");--> statement-breakpoint
CREATE INDEX "class_series_created_by_staff_id_fk_idx" ON "class_series" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "class_series_location_id_fk_idx" ON "class_series" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "class_series_main_instructor_id_fk_idx" ON "class_series" USING btree ("main_instructor_id");--> statement-breakpoint
CREATE INDEX "class_series_room_id_fk_idx" ON "class_series" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "class_series_supporting_instructors_instructor_id_fk_idx" ON "class_series_supporting_instructors" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "class_supporting_instructors_instructor_id_fk_idx" ON "class_supporting_instructors" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "classes_cancelled_by_staff_id_fk_idx" ON "classes" USING btree ("cancelled_by_staff_id");--> statement-breakpoint
CREATE INDEX "classes_class_type_id_fk_idx" ON "classes" USING btree ("class_type_id");--> statement-breakpoint
CREATE INDEX "classes_created_by_staff_id_fk_idx" ON "classes" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "classes_location_id_fk_idx" ON "classes" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "classes_main_instructor_id_fk_idx" ON "classes" USING btree ("main_instructor_id");--> statement-breakpoint
CREATE INDEX "classes_room_id_fk_idx" ON "classes" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "classes_series_id_fk_idx" ON "classes" USING btree ("series_id");--> statement-breakpoint
CREATE INDEX "corporate_requests_client_id_fk_idx" ON "corporate_requests" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "corporate_requests_corporate_package_id_fk_idx" ON "corporate_requests" USING btree ("corporate_package_id");--> statement-breakpoint
CREATE INDEX "corporate_requests_resolved_by_staff_id_fk_idx" ON "corporate_requests" USING btree ("resolved_by_staff_id");--> statement-breakpoint
CREATE INDEX "corporate_session_supporting_instructors_instructor_id_fk_idx" ON "corporate_session_supporting_instructors" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_cancelled_by_staff_id_fk_idx" ON "corporate_sessions" USING btree ("cancelled_by_staff_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_corporate_package_id_fk_idx" ON "corporate_sessions" USING btree ("corporate_package_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_created_by_staff_id_fk_idx" ON "corporate_sessions" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_location_id_fk_idx" ON "corporate_sessions" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_main_instructor_id_fk_idx" ON "corporate_sessions" USING btree ("main_instructor_id");--> statement-breakpoint
CREATE INDEX "corporate_sessions_room_id_fk_idx" ON "corporate_sessions" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "manual_payroll_entries_created_by_staff_id_fk_idx" ON "manual_payroll_entries" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "manual_payroll_entries_instructor_id_fk_idx" ON "manual_payroll_entries" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "pt_request_slots_pt_request_id_fk_idx" ON "pt_request_slots" USING btree ("pt_request_id");--> statement-breakpoint
CREATE INDEX "pt_requests_class_type_id_fk_idx" ON "pt_requests" USING btree ("class_type_id");--> statement-breakpoint
CREATE INDEX "pt_requests_client_id_fk_idx" ON "pt_requests" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "pt_requests_co_client_id_fk_idx" ON "pt_requests" USING btree ("co_client_id");--> statement-breakpoint
CREATE INDEX "pt_requests_debited_client_package_id_fk_idx" ON "pt_requests" USING btree ("debited_client_package_id");--> statement-breakpoint
CREATE INDEX "pt_requests_location_id_fk_idx" ON "pt_requests" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "pt_requests_resolved_by_staff_id_fk_idx" ON "pt_requests" USING btree ("resolved_by_staff_id");--> statement-breakpoint
CREATE INDEX "pt_session_clients_client_id_fk_idx" ON "pt_session_clients" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "pt_session_clients_tenant_id_fk_idx" ON "pt_session_clients" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "pt_session_supporting_instructors_instructor_id_fk_idx" ON "pt_session_supporting_instructors" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "pt_session_supporting_instructors_tenant_id_fk_idx" ON "pt_session_supporting_instructors" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "pt_sessions_cancelled_by_staff_id_fk_idx" ON "pt_sessions" USING btree ("cancelled_by_staff_id");--> statement-breakpoint
CREATE INDEX "pt_sessions_instructor_id_fk_idx" ON "pt_sessions" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "pt_sessions_location_id_fk_idx" ON "pt_sessions" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "pt_sessions_room_id_fk_idx" ON "pt_sessions" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "pt_sessions_scheduled_by_staff_id_fk_idx" ON "pt_sessions" USING btree ("scheduled_by_staff_id");--> statement-breakpoint
CREATE INDEX "workshop_days_room_id_fk_idx" ON "workshop_days" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "workshop_images_workshop_id_fk_idx" ON "workshop_images" USING btree ("workshop_id");--> statement-breakpoint
CREATE INDEX "workshop_instructors_instructor_id_fk_idx" ON "workshop_instructors" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "workshop_tier_days_workshop_day_id_fk_idx" ON "workshop_tier_days" USING btree ("workshop_day_id");--> statement-breakpoint
CREATE INDEX "workshop_tiers_workshop_id_fk_idx" ON "workshop_tiers" USING btree ("workshop_id");--> statement-breakpoint
CREATE INDEX "workshops_cancelled_by_staff_id_fk_idx" ON "workshops" USING btree ("cancelled_by_staff_id");--> statement-breakpoint
CREATE INDEX "workshops_created_by_staff_id_fk_idx" ON "workshops" USING btree ("created_by_staff_id");--> statement-breakpoint
CREATE INDEX "workshops_location_id_fk_idx" ON "workshops" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "bookings_applied_promo_code_id_fk_idx" ON "bookings" USING btree ("applied_promo_code_id");--> statement-breakpoint
CREATE INDEX "bookings_applied_promotion_id_fk_idx" ON "bookings" USING btree ("applied_promotion_id");--> statement-breakpoint
CREATE INDEX "bookings_class_id_fk_idx" ON "bookings" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX "bookings_client_id_fk_idx" ON "bookings" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "bookings_client_package_id_fk_idx" ON "bookings" USING btree ("client_package_id");--> statement-breakpoint
CREATE INDEX "bookings_pt_session_id_fk_idx" ON "bookings" USING btree ("pt_session_id");--> statement-breakpoint
CREATE INDEX "bookings_purchase_id_fk_idx" ON "bookings" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "bookings_workshop_id_fk_idx" ON "bookings" USING btree ("workshop_id");--> statement-breakpoint
CREATE INDEX "bookings_workshop_tier_id_fk_idx" ON "bookings" USING btree ("workshop_tier_id");--> statement-breakpoint
CREATE INDEX "cancellations_booking_id_fk_idx" ON "cancellations" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "cancellations_client_id_fk_idx" ON "cancellations" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "check_ins_checked_in_by_staff_id_fk_idx" ON "check_ins" USING btree ("checked_in_by_staff_id");--> statement-breakpoint
CREATE INDEX "check_ins_tenant_id_fk_idx" ON "check_ins" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "audit_log_actor_staff_id_fk_idx" ON "audit_log" USING btree ("actor_staff_id");--> statement-breakpoint
CREATE INDEX "manual_adjustments_acted_by_staff_id_fk_idx" ON "manual_adjustments" USING btree ("acted_by_staff_id");--> statement-breakpoint
CREATE INDEX "manual_adjustments_client_id_fk_idx" ON "manual_adjustments" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "manual_adjustments_client_package_id_fk_idx" ON "manual_adjustments" USING btree ("client_package_id");--> statement-breakpoint
CREATE INDEX "payment_customers_client_id_fk_idx" ON "payment_customers" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "purchases_client_id_fk_idx" ON "purchases" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "stripe_payments_booking_id_fk_idx" ON "stripe_payments" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "stripe_payments_client_id_fk_idx" ON "stripe_payments" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "stripe_payments_client_package_id_fk_idx" ON "stripe_payments" USING btree ("client_package_id");--> statement-breakpoint
CREATE INDEX "stripe_payments_purchase_id_fk_idx" ON "stripe_payments" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "email_templates_updated_by_staff_id_fk_idx" ON "email_templates" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "marketing_content_updated_by_staff_id_fk_idx" ON "marketing_content" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "waiver_updated_by_staff_id_fk_idx" ON "waiver" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "waiver_signatures_tenant_id_fk_idx" ON "waiver_signatures" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "inbox_items_read_by_staff_id_fk_idx" ON "inbox_items" USING btree ("read_by_staff_id");--> statement-breakpoint
CREATE INDEX "leave_pools_tenant_id_fk_idx" ON "leave_pools" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "leave_requests_decided_by_staff_id_fk_idx" ON "leave_requests" USING btree ("decided_by_staff_id");--> statement-breakpoint
CREATE INDEX "leave_requests_instructor_id_fk_idx" ON "leave_requests" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "feature_flags_updated_by_staff_id_fk_idx" ON "feature_flags" USING btree ("updated_by_staff_id");--> statement-breakpoint
CREATE INDEX "client_auth_sessions_claimed_tenant_id_fk_idx" ON "client_auth_sessions" USING btree ("claimed_tenant_id");--> statement-breakpoint
CREATE INDEX "staff_auth_sessions_claimed_tenant_id_fk_idx" ON "staff_auth_sessions" USING btree ("claimed_tenant_id");