export const CLASS_CANCELLATION_HOURS = 12;
export const PRIVATE_SESSION_CANCELLATION_HOURS = 12;
export const PRIVATE_CONFIRMATION_SLA_HOURS = 12;
export const LAST_MINUTE_THRESHOLD = 3;

export const DEFAULT_POLICY = {
  classCancelHours: CLASS_CANCELLATION_HOURS,
  privateCancelHours: PRIVATE_SESSION_CANCELLATION_HOURS,
  privateSlaHours: PRIVATE_CONFIRMATION_SLA_HOURS,
  lastMinuteThreshold: LAST_MINUTE_THRESHOLD,
};
